// apps/react-app/src/app/pages/home/Home.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import './Home.scss';

const Home: React.FC = () => {
  return (
    <div className="home-container">
      <section className="intro">
        <p>Welcome to my frontend lab.</p>
        <p>
          This project explores interesting React patterns and component
          architectures
        </p>
      </section>

      <section className="features">
        <div className="feature-grid">
          <div className="feature-card">
            <h3>Lion based locked selection demo</h3>
            <p>Implementing lion based locked selection control</p>
            <Link to="/locked-selection" className="feature-link">
              View Locked selection demo
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Home;

// apps/angular-app/src/app/features/home/home.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'fl-home',
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss',
  imports: [RouterModule],
})
export class HomeComponent {}

<div class="home-container">
  <section class="intro">
    <h1>Angular Experiments</h1>
    <p>Welcome to my Angular frontend lab.</p>
    <p>
      This project explores interesting Angular patterns and component
      architectures
    </p>
  </section>

  <section class="features">
    <div class="feature-grid">
      <div class="feature-card">
        <h3>Hierarchical Folder Tree</h3>
        <p>Implementing checkbox based hierarchical folder tree</p>
        <a routerLink="/tree" class="feature-link">View Tree Demo</a>
      </div>
    </div>
  </section>
</div>
