// apps/react-app/src/app/components/shared/header/Header.tsx
import React, { useState } from 'react';
import { NavLink } from 'react-router-dom';
import './Header.scss';

const Header: React.FC = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  const closeMenu = () => {
    setIsMenuOpen(false);
  };

  return (
    <header className="header">
      <div className="header-content">
        {/* Hamburger Menu Button on the left */}
        <button
          className={`menu-button ${isMenuOpen ? 'active' : ''}`}
          onClick={toggleMenu}
          aria-label="Toggle navigation menu"
        >
          <span className="material-symbols-outlined">menu</span>
        </button>

        <div className="logo">
          <h1>Front lab</h1>
        </div>

        {/* Empty div to maintain flex spacing */}
        <div className="spacer"></div>

        {/* Navigation Menu */}
        <nav className={`main-nav ${isMenuOpen ? 'open' : ''}`}>
          <NavLink to="/" onClick={closeMenu}>
            Home
          </NavLink>
          <NavLink to="/locked-selection" onClick={closeMenu}>
            Lion locked selection
          </NavLink>
        </nav>

        {/* Overlay for mobile menu */}
        {isMenuOpen && (
          <div
            className="menu-overlay"
            onClick={closeMenu}
            tabIndex={0}
            onKeyDown={closeMenu}
          ></div>
        )}
      </div>
    </header>
  );
};

export default Header;

// apps/angular-app/src/app/shared/header/header.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'fl-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
  imports: [RouterModule, CommonModule],
  standalone: true,
})
export class HeaderComponent {
  public isMenuOpen = false;

  public toggleMenu(): void {
    this.isMenuOpen = !this.isMenuOpen;
  }

  public closeMenu(): void {
    this.isMenuOpen = false;
  }
}

<header class="header">
  <div class="header-content">
    <!-- Hamburger Menu Button on the left -->
    <button
      class="menu-button"
      (click)="toggleMenu()"
      [class.active]="isMenuOpen"
      aria-label="Toggle navigation menu"
    >
      <span class="material-symbols-outlined">menu</span>
    </button>

    <div class="logo">
      <h1>Front lab</h1>
    </div>

    <!-- Empty div to maintain flex spacing -->
    <div class="spacer"></div>

    <!-- Mobile Navigation Menu -->
    <nav class="main-nav" [class.open]="isMenuOpen">
      <a routerLink="/" routerLinkActive="active" (click)="closeMenu()">Home</a>
      <a
        routerLink="/folder-tree"
        routerLinkActive="active"
        (click)="closeMenu()"
        >Folder Tree</a
      >
      <a
        routerLink="/lion-locked-selection"
        routerLinkActive="active"
        (click)="closeMenu()"
        >Lion locked selection</a
      >
      <a
        routerLink="/lion-integer-digit-match"
        routerLinkActive="active"
        (click)="closeMenu()"
      >Lion integer digit match</a
      >
    </nav>

    <!-- Overlay for mobile menu -->
    @if (isMenuOpen) {
    <div
      class="menu-overlay"
      (click)="closeMenu()"
      (keydown)="closeMenu()"
      tabindex="0"
    ></div>
    }
  </div>
</header>
